Submodule: use ssh url
Because github recently changed something with their ssl setup,
git clone on https urls breaks with the below error for older versions
of openssl.

    error: error:0D0C50A1:asn1 encoding routines:ASN1_item_verify:unknown message digest algorithm while accessing https://github.com